Document: xtest
Title: Debian xtest Manual
Author: <insert document author here>
Abstract: This manual describes what xtest is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/xtest/xtest.sgml.gz

Format: postscript
Files: /usr/share/doc/xtest/xtest.ps.gz

Format: text
Files: /usr/share/doc/xtest/xtest.text.gz

Format: HTML
Index: /usr/share/doc/xtest/html/index.html
Files: /usr/share/doc/xtest/html/*.html
